version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          command: python setup.py sdist
          name: Generate distribution archive
  fury:
    executor: python/default
    steps:
      - run:
          command: curl -F package=@${ls *.tar.gz} https://$FURY_TOKEN@push.fury.io/op01/
          name: Publish

workflows:
  main:
    jobs:
      - build
      - fury:
          requires:
            - build
          context:
            - gemfury
          filters:
            branches:
              only: master

