version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build_and_publish:
    executor: python/default
    steps:
      - checkout
      - run:
          command: python setup.py sdist
          name: Generate distribution archive
      - run:
          command: |
            curl -F package=@`ls dist/*.tar.gz` https://$FURY_TOKEN@push.fury.io/op01/
          name: Publish

workflows:
  main:
    jobs:
      - build_and_publish:
          context:
            - gemfury
          filters:
            branches:
              only: 
                - master
                - circleci-project-setup

